apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-django
  region: us-east-1
  version: "1.29"

availabilityZones: 
  - us-east-1a
  - us-east-1b  

managedNodeGroups:
- name: spot-mid
  instanceTypes: ["t3.medium"]            
  desiredCapacity: 1
  minSize: 1
  maxSize: 2
  spot: true
  maxPodsPerNode: 35  
  ssh:
    allow: true
    publicKeyName: TZ          
