apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
spec:
  type: ClusterIP
  selector: {{- include "demo.selectorLabels" . | nindent 4 }}
  ports:
  - port: 8000
    targetPort: {{ .Values.image.containerPort }}
